name: selenium - poc de prisa
env:
  OS: ubuntu-latest

# run-name: selenium - ${{ inputs.os }} - ${{ inputs.browser }}
run-name: selenium - $OS - ${{ inputs.browser }}

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Elije el navegador
        required: true
        options:
          - chrome
          - firefox
          - safari

jobs:
  selenium:
    # runs-on: ${{ github.event.inputs.os }}
    runs-on: ${{ env.OS }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Test Docker is up
        run: docker info

      - name: Run Selenium with Maven
        run: mvn clean test -Dbrowser=${{ github.event.inputs.browser }}

      - name: Generate artifact for Extent PDF
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report_pdf
          path: ./extent-reports/pdf

      - name: Generate artifact for ExtentReports Spark HTML
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report_html
          path: ./extent-reports/spark

      - name: Generate artifact for Allure Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report_allure
          path: ./allure-results

      - name: Generate artifact for video recording
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report_video
          path: ./test-recordings
          
        # - name: Deploy report index to GitHub Page
        # uses: JamesIves/github-pages-deploy-action@4.1.5
        # with:
        # branch: gh-pages
        # folder: ./reports/spark
          
  allure:
    needs: selenium
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: report_allure
          path: ./allure-results
            
      - name: Get AllureReports history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Get AllureReports results
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Prepare AllureReports deploy to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
